spring:
  application:
    name: java-service
  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: username
    password: password

  # H2 Console 설정
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  expiration-minutes: 30
  secret-key: sparta-local-authenticate-secret-key
