### 일반 사용자 회원 가입 API
POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "user",
  "password": "password",
  "nickname": "아린"
}

### 일반 사용자 로그인 API
POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}
> {%
  client.global.set("token", response.headers.valueOf("Authorization"))
%}

### 테스트
GET http://localhost:8080/api/test
Content-Type: application/json
Authorization: {{token}}
